### ISSUE TITLE
please help me to disable vertical plane detection in arcore

### ISSUE THREAD

**Issue by ishaang10** [olucurious/Awesome-ARCore#6]
here goes my code

  @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        arFragment=(ArFragment) getSupportFragmentManager().findFragmentById(R.id.ux_fragment);

        ModelRenderable.builder().setSource(this,Uri.parse("armchair.sfb")).build()
                .thenAccept(modelRenderable -> chickenren=modelRenderable).exceptionally(throwable -> {
            Toast.makeText(this,"unable",Toast.LENGTH_LONG).show();
            return null;
        });

        arFragment.setOnTapArPlaneListener(
                (HitResult hitResult, Plane plane, MotionEvent motionEvent)->{

                    if(plane.getType() != Plane.Type.HORIZONTAL_UPWARD_FACING)
                        return;

                    Anchor anchor = hitResult.createAnchor();
                    AnchorNode anchorNode = new AnchorNode(anchor);
                    anchorNode.setParent(arFragment.getArSceneView().getScene());

                    TransformableNode chicken = new TransformableNode(arFragment.getTransformationSystem());
                    chicken.setParent(anchorNode);
                    chicken.setRenderable(chickenren);
                    chicken.select();

                });

    }

**Comment by olucurious** [comment]
Sorry for the late response, I was going to ask if you've been able to resolve the issue

**Comment by ishaang10** [comment]
yes i have solved the issue .thanx
